apiVersion: v1
kind: Service
metadata:
  name: yolox-s
  namespace: yolox-edge
  labels:
    app.kubernetes.io/name: yolox-s
spec:
  type: NodePort
  selector:
    app: yolox-s
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30800     # Reachable at http://<node-ip>:30800
    protocol: TCP
